title: atestera
favicon: /images/favicon-isomer.ico
shareicon: /images/isomer-logo.svg
facebook-pixel: te
google_analytics: ''
colors:
  primary-color: '#b6316b'
  secondary-color: '#4372d6'
  media-colors:
    - title: media-color-one
      color: '#49759a'
    - title: media-color-two
      color: '#744d9f'
    - title: media-color-three
      color: '#00838f'
    - title: media-color-four
      color: '#00838f'
    - title: media-color-five
      color: '#00838f'
